# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-29 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20161112_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='createtime',
            field=models.DateField(),
        ),
    ]
