# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-29 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20170529_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='views',
            new_name='view',
        ),
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.CharField(default=b'static/images/default.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='createtime',
            field=models.DateField(auto_now=True),
        ),
    ]
