# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-30 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cover',
            field=models.FileField(null=True, upload_to=b'cover_image'),
        ),
    ]
