# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-07 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under_comments', to='firstapp.Video'),
        ),
    ]
