# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-08 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_auto_20170607_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[(b'like', b'like'), (b'dislike', b'dislike'), (b'normal', b'normal')], max_length=10)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='firstapp.Video')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_tickets', to='firstapp.UserProfile')),
            ],
        ),
    ]
