# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-13 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_auto_20170613_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=b'cover_image'),
        ),
    ]
