# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-18 16:04
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_auto_20170615_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True),
        ),
    ]
